version: "3"
services:
  try-nextjs-db:
    image: postgres:10
    container_name: "prisma_db"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "15432:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
